apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-server
  labels:
    app: vanilla
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: vanilla
  template:
    metadata:
      labels:
        app: vanilla
    spec:
      containers:
      - name: nginx
        image: {{ .Values.image.repository }}
        ports:
        - containerPort: 80
          #volumeMounts:
          #  - name: nginx-config
          #    mountPath: /etc/nginx/conf.d/
          #    subPath: nginx.conf
        #- name: nginx-exporter
        #  image: 'nginx/nginx-prometheus-exporter:0.10.0'
         # args:
          #  - '-nginx.scrape-uri=http://104.198.236.179/nginx_status'
          #resources:
           # limits:
            #  memory: 128Mi
             # cpu: 500m
          #ports:
           # - containerPort: 9113
      #volumes:
       # - name: nginx-config
          
