apiVersion: v1
kind: Service
metadata:
  name: vanilla-svc
  labels:
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: vanilla
